### ISSUE TITLE
app not installed as package appears to be invalid

### ISSUE THREAD

**Issue by mikektmobile** [msintuneappsdk/intune-app-wrapping-tool-android#80] opened 2023-04-24 20:13 UTC
After wrapping our .apk file with android sdk wrapping tool it says successful
Built apk into: C:\Users\mike.kt\AppData\Local\Temp\IntuneAppWrappingTool-7094597179150155580\appWrapper_5530558032404902904.apk
The package name for this app is 'com.socialchorus.daga.android.googleplay'. If you need to specify the package name during deployment, please use this one.
The application was successfully wrapped.

Then we resign the app with our cert successfully
>>> Signer
    X.509, CN=Social Chorus, OU=S, O=C, C=US
    Signature algorithm: SHA256withRSA, 2048-bit key
    [trusted certificate]

jar signed.

Warning: 
The signer's certificate is self-signed.
mike.kt@MBP14-2021-F2H-1p-mk apk % jarsigner -verify -verbose /Users/mike.kt/Desktop/apk/firstupwrapped.apk 

When we go to install the app we get app not installed as package appears to be invalid.  Im not sure what is wrong the app before wrapping was tested and working.

**Comment by mikektmobile** [comment] 2023-05-05 15:00
Still no luck with this

**Comment by meghandaly** [comment] 2023-05-22 21:20
This appears to be a duplicate of #79. Closing this and will continue the conversation there.

**Closed by meghandaly** 2023-05-22 21:20 UTC
Labels: Need More Information
