### ISSUE TITLE
"Error - Failed to load app resource table while wrapping APK with INTUNE SDK.

### ISSUE THREAD

**Issue by sagar-sg** [msintuneappsdk/intune-app-wrapping-tool-android#60] opened 2022-04-10 12:00 UTC
**Bug(Issue):**
I have tried to wrap Android released as well as unsigned APK getting an error as "Failed to load app resource table."

[IntuneAppWrappingToolLog_20220404_174919.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/8458887/IntuneAppWrappingToolLog_20220404_174919.txt)

**Intune app wrapping tool:**
Version for intune -- [Version 1.0.3610.6](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/commit/298de64fee719feea48608197af163c081923484)
Platform -Android

**Additional Info**
The Issue comes on any newly created Android App as well. Check
[IntuneAppWrappingToolLog_20220404_162025.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/8458892/IntuneAppWrappingToolLog_20220404_162025.txt)

Also, a version for intune SDK - Version 1.0.3610.6 does not support Android API level 32.
Please suggest solution to above issues.

**Comment by rygo-msft** [comment] 2022-05-03 16:03
This appears to be a duplicate of #62.
Please follow that issue as it has further details 

 WRN C:\Users\sagar\AppData\Local\Temp\IntuneAppWrappingTool-4996429882418164810\sourceApk\res\values-v31\colors.xml:55: error: resource android:color/Indigo_800 is private.
WRN C:\Users\sagar\AppData\Local\Temp\IntuneAppWrappingTool-4996429882418164810\sourceApk\res\values-v31\colors.xml:56: error: resource android:color/Indigo_700 is private.
WRN C:\Users\sagar\AppData\Local\Temp\IntuneAppWrappingTool-4996429882418164810\sourceApk\res\values-v31\colors.xml:58: error: resource android:color/GM2_grey_800 is private.
WRN C:\Users\sagar\AppData\Local\Temp\IntuneAppWrappingTool-4996429882418164810\sourceApk\res\values-v31\colors.xml:59: error: resource android:color/Blue_800 is private.
WRN C:\Users\sagar\AppData\Local\Temp\IntuneAppWrappingTool-4996429882418164810\sourceApk\res\values-v31\colors.xml:60: error: resource android:color/Blue_700 is private.

**Closed by rygo-msft** 2022-05-03 16:03 UTC

**Comment by meghandaly** [comment] 2022-05-03 18:32
@sagar-sg A feature request for API 32 targeting support has been opened, please follow #64 for updates / add additional context if you desire.
