### ISSUE TITLE
[Feature Request] Urgent Need to Support for Target API level 32+ for Capacitor v4 !

### ISSUE THREAD

**Issue by xzetic05** [msintuneappsdk/intune-app-wrapping-tool-android#73] opened 2022-11-11 06:17 UTC
## Information
We are using Ionic Capacitor v4 and major requirement is to set the compileSdkVersion and targetSdkVersion to 32, there is no possible way to downgrade since our enterprise application is using Company Portal and need to be wrap by this tool.

### Feature Request
Urgent Need to Support for Target API level 32+ for Capacitor v4

### Reason for Request
Our Enterprise Company is using the Company Portal to publish our enterprise app and it is required to support latest SDK version of Android.

### Preferred Solution

[TODO - Detail the preferred solution.]

## Questions to Ask Before Submission

1. Has the feature you are requesting already been submitted? **No**
2. Are you using the latest App Wrapper version? **Yes**

**Comment by rygo-msft** [comment] 2022-11-14 22:08
Duplicate of #64

**Closed by rygo-msft** 2022-11-14 22:08 UTC
Labels: Feature Request
