### ISSUE TITLE
Deep link to company portal application

### ISSUE THREAD

**Issue by Sylvia310800** [msintuneappsdk/intune-app-wrapping-tool-android#58] opened 2022-03-21 05:03 UTC
companyportal:ApplicationId=<app-id>

currently I am using the above to redirect user to the company portal. However, user has to select between the test and production app. Is there any way to deep link to a specific app id?

**Comment by meghandaly** [comment] 2022-03-24 16:21
@Sylvia310800 I do not recognize the configuration `companyportal:ApplicationId=` in question.

Is this in relation to a wrapped Android app? If not, this repository is not the correct place for this issue.

**Comment by meghandaly** [comment] 2022-05-03 14:50
Closing because our team has not received additional information within the last 30 days and the issue is not actionable.

If you are still experiencing this issue, please provide the requested information and reopen the issue.

**Closed by meghandaly** 2022-05-03 14:50 UTC
Labels: Closed - Not Enough Info
