### ISSUE TITLE
[Feature Request] Support for Target API level 33

### ISSUE THREAD

**Issue by poladiaraj** [msintuneappsdk/intune-app-wrapping-tool-android#70] opened 2022-10-06 03:50 UTC
### Feature Request

Increase targeting support from Target API level 31 to API level 33.

### Reason for Request

Support for the latest APIs.

### Preferred Solution

A new App Wrapper release with Target API level 33 support.

## Questions to Ask Before Submission

1. Has the feature you are requesting already been submitted? - No
2. Are you using the latest App Wrapper version? - Yes

**Comment by ryanliljestrom** [comment] 2022-11-08 12:10
Also interested in an update to the Android wrapping tool. We use this to wrap third-party developed applications before deploying them to our internal company store, and it looks like the wrapping tool is a few [versions behind the sdk](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases)

**Comment by rygo-msft** [comment] 2022-11-14 22:08
Duplicate of #64

**Closed by rygo-msft** 2022-11-14 22:08 UTC
Labels: Feature Request
