### ISSUE TITLE
Not getting the pin screen in Android

### ISSUE THREAD

**Issue by kritid11** [msintuneappsdk/intune-app-wrapping-tool-android#53] opened 2021-12-16 06:06 UTC
I have followed the taskR app. In first attempt the acquire token graph fails. So I call remediate compliance. It succeeds with COMPLIANT status. Then I reinitiate acquiring token, and it works. 

However, I am not being asked the PIN. My app is under default MAM app protection policy which should ask for 4 pin code.

**Comment by codylund** [comment] 2021-12-29 16:50
Hi @kritid11, it sounds like you may be having issues manually integrating the MAM SDK in your app. This repo is specifically for issues involving the Intune Android App Wrapping tool. If the issue is still occurring, can you open a new issue in the [ms-intune-app-sdk-android repo](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) with the following additional information? 

- Does this occur immediately following enrollment, or after the app has been enrolled for a while? 
- After enrolling, did you ever see the "Get Access" screen? Generally, you will not be prompted for a PIN until you have successfully enrolled, navigated to a managed Activity, and been shown this screen.
- If you have a consistent repro, can you reproduce the issue and immediately collect logs via the Company Portal? Steps are as follows:
   1. Open the Company Portal. If not logged in, press the "..." menu button in the top right. If already logged in, press the hamburger icon in the top left.
   2. Click Help -> Email Support -> Upload Logs Only.
   3. Share the Incident ID displayed here.

**Comment by codylund** [comment] 2021-12-29 16:52
Closing the issue in this repo as this does not appear to be an issue involving the Intune Android App Wrapping tool.

**Closed by codylund** 2021-12-29 16:52 UTC
